### PR TITLE
Add harperdb-connect

### LINKED ISSUE #12: Integrate harperdb_connect
It might be worth exploring integrating [harperdb-connect](https://github.com/Ethan-Arrowood/harperdb-connect) to replace utility/harperdbCallout.js.  It is cleaner.

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
Todo:
- [x] Update all `callHarperDB()` method calls to `then/catch` chains or `async/await` blocks (remove callbacks)

Files that call `.callHarperDB()` method (check means they have been promisified):
- [x] [hdb_studio.js](https://github.com/HarperDB/HarperDB_Studio/blob/master/hdb_studio.js)
- [x] [routes/explore.js](https://github.com/HarperDB/HarperDB_Studio/blob/master/routes/explore.js)
- [x] [routes/live_link.js](https://github.com/HarperDB/HarperDB_Studio/blob/master/routes/live_link.js)
- [x] [routes/logs.js](https://github.com/HarperDB/HarperDB_Studio/blob/master/routes/logs.js)
- [x] [routes/schema.js](https://github.com/HarperDB/HarperDB_Studio/blob/master/routes/schema.js)
- [x] [routes/security.js](https://github.com/HarperDB/HarperDB_Studio/blob/master/routes/security.js)
- [x] [routes/user_detail.js](https://github.com/HarperDB/HarperDB_Studio/blob/master/routes/user_detail.js)
- [x] [utility/favoritesQuery.js](https://github.com/HarperDB/HarperDB_Studio/blob/master/utility/favoritesQuery.js)
- [x] [utility/harperDBCallout.js](https://github.com/HarperDB/HarperDB_Studio/blob/master/utility/harperDBCallout.js)

This is an update branch from #19 and will close #12 

**This is not ready to be merged**

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
Regarding file [`hdb_studio.js`](https://github.com/HarperDB/HarperDB_Studio/blob/master/hdb_studio.js) and commits https://github.com/HarperDB/HarperDB_Studio/pull/32/commits/0a086b3fbd58c044fe604895b0a3bc9b0b300ea5 and https://github.com/HarperDB/HarperDB_Studio/pull/32/commits/22a0d6be6296b1892ee893d672f99e9e698b52ec

@kylebernhardy @elipalmer Question regarding roles/users:

Is it `super_admin` or `super_user`? In the current master branch, the hdb_studio file assigns the property `super_admin`, but internally I believe harperdb uses `super_user` to determine the permissions of a _super admin/user_. 

I figured out what hdb uses internally by running the `list_users` operation in postman. My admin account (which I create when installing HarperDB) gets the default role **super_user** (see image below)
screen shot 2018-07-08 at 6 43 00 pm

I've currently updated [`hdb_studio.js`](https://github.com/HarperDB/HarperDB_Studio/pull/32/commits/22a0d6be6296b1892ee893d672f99e9e698b52ec#diff-3e3e1df06b204e4352be7b5429a89968) to user `super_user` as that is what HarperDB is using internally; but I'd like you two to confirm this is proper use.

**Comment by Ethan-Arrowood** [comment]
Here is some issues I came up with while working on this PR. When I get a chance I'll open actual issues so we can share them with other developers.
HarperDB_Studio Issues
- [Minor] Convert all JS to ES6 standards
  - ‘var’ -> ‘let’ or ‘const’
  - Utilize object destructuring where applicable
  - Replace functions that return promises with async/await functions
  - Replace string concatenations with template strings literals 
- [Patch] Remove spaghetti code in favoritesQuery
  - There is probably more spaghetti code in other places
  - In ‘favoritesQuery’, the two methods ‘createLiveLinkTable’ and ‘createUserFavoriteTable’ can be simplified into one function with an extra function argument.
- [Major] Implement proper error handling
  - Differentiate between network errors (connection between app and db) 
    and database errors (invalid auth, bad query, etc.)
  - Use error status codes from HarperDB to give better error messages to the user
- [Minor] Add argument assertions for all major functions
  - assert things like data type, existence, and enumerable values
- [Minor] Add ESLint configuration

**Comment by elipalmer** [comment]
Sorry for the delay on this PR.  I am reviewing it now.

**Comment by Ethan-Arrowood** [comment]
Okay I'll work through these files and complete the following:
- Remove unnecessary comments (pretty much all of them)
- Change `var` to `let` or `const`
- Update promise chains to async/await methods
- Make sure all await statements are followed by `catch`

**Comment by elipalmer** [comment]
Hey Ethan, is this still in work?

**Comment by Ethan-Arrowood** [comment]
Yes it is, ( was actually thinking about it today ). I have GitHub Hackcon
this weekend, but i'll make sure to find sometime for this in the coming
week :)

**Comment by Ethan-Arrowood** [comment]
Ignore the commit mess rn. I'm going to clean it all up at the end with a nice `rebase` :+1:

**Comment by Ethan-Arrowood** [comment]
Closing this because I'm going to be overwriting this branch with a cleaner version.

**Pull request closed without merging**
