### PR TITLE
[Discontinued] [See #32] Integrate hdb connect

### LINKED ISSUE #12: Integrate harperdb_connect
It might be worth exploring integrating [harperdb-connect](https://github.com/Ethan-Arrowood/harperdb-connect) to replace utility/harperdbCallout.js.  It is cleaner.

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
Closes #12 Also, I left in a `true || ` thing on `hdb_studio.js` so you can run this in any version of Node you want (we should solve #18 asap). Anyone reviewing this I encourage you check it out locally and make sure it runs on all use cases. Until we get unit tests going core changes like this can be risky! ALSO please please open issues on [`harperdb-connect`](https://github.com/Ethan-Arrowood/harperdb-connect) if you find any or have any recommendations.

---
This change is [Reviewable](https://reviewable.io/reviews/harperdb/harperdb_studio/19)

### CODE REVIEW

**Comment by elipalmer** [comment]
*[utility/harperDBCallout.js, line 6 at r1](https://reviewable.io/reviews/harperdb/harperdb_studio/19#-LEKrw5r960iF95nKT_1:-LEKrw5r960iF95nKT_2:bqps3dv) ([raw file](https://github.com/harperdb/harperdb_studio/blob/6b40e4078fe9f7371e0e8b95e3623cb11329e1e9/utility/harperDBCallout.js#L6)):*
> ```JavaScript
>     const db = new HarperDBConnect();
>     
>     db.setAuthorization(call_object.username, call_object.password)
> ```

It looks like setAuthorization can throw exceptions, add a try/catch.

---


*Comments from [Reviewable](https://reviewable.io/reviews/harperdb/harperdb_studio/19)*

**Comment by elipalmer** [comment]
*[utility/harperDBCallout.js, line 14 at r1](https://reviewable.io/reviews/harperdb/harperdb_studio/19#-LEKs3VhEFiKHVkbVJRy:-LEKs3VhEFiKHVkbVJRz:bsug77d) ([raw file](https://github.com/harperdb/harperdb_studio/blob/6b40e4078fe9f7371e0e8b95e3623cb11329e1e9/utility/harperDBCallout.js#L14)):*
> ```JavaScript
>     ) : (
>         `http://${endpoint_url}:${endpoint_port}`
>     )
> ```

Nitpick: end with a semi-colon

---


*Comments from [Reviewable](https://reviewable.io/reviews/harperdb/harperdb_studio/19)*

**Comment by elipalmer** [comment]
*[utility/harperDBCallout.js, line 35 at r1](https://reviewable.io/reviews/harperdb/harperdb_studio/19#-LEKsBdZ4ElmK5gJuHKH:-LEKsBdZ4ElmK5gJuHKI:bimd82e) ([raw file](https://github.com/harperdb/harperdb_studio/blob/6b40e4078fe9f7371e0e8b95e3623cb11329e1e9/utility/harperDBCallout.js#L35)):*
> ```JavaScript
> module.exports = {
>     callHarperDB: callHarperDB
> }
> ```

nitpick: semicolon

---


*Comments from [Reviewable](https://reviewable.io/reviews/harperdb/harperdb_studio/19)*

**Comment by elipalmer** [comment]
*[utility/harperDBCallout.js, line 1 at r1](https://reviewable.io/reviews/harperdb/harperdb_studio/19#-LEKsEyE5A_lB6yG4s3p:-LEKsEyE5A_lB6yG4s3q:bh9adck) ([raw file](https://github.com/harperdb/harperdb_studio/blob/6b40e4078fe9f7371e0e8b95e3623cb11329e1e9/utility/harperDBCallout.js#L1)):*
> ```JavaScript
> const { HarperDBConnect } = require('harperdb-connect');
> ```

The file doesn't have "use strict", but it should.  Could you add it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/harperdb/harperdb_studio/19)*

**Comment by elipalmer** [comment]
*[config/config.json, line 2 at r1](https://reviewable.io/reviews/harperdb/harperdb_studio/19#-LEKsKcwDJTl4YL7FdF5:-LEKsKcwDJTl4YL7FdF6:b-fggdqa) ([raw file](https://github.com/harperdb/harperdb_studio/blob/6b40e4078fe9f7371e0e8b95e3623cb11329e1e9/config/config.json#L2)):*
> ```JSON
> {
>   "default_host":"http://localhost",
> ```

Good catch, this is much more clear.

---


*Comments from [Reviewable](https://reviewable.io/reviews/harperdb/harperdb_studio/19)*

**Comment by elipalmer** [comment]
*[utility/harperDBCallout.js, line 28 at r1](https://reviewable.io/reviews/harperdb/harperdb_studio/19#-LEKuvilCSr2cikJMYds:-LEKuvilCSr2cikJMYdt:b-ekoyto) ([raw file](https://github.com/harperdb/harperdb_studio/blob/6b40e4078fe9f7371e0e8b95e3623cb11329e1e9/utility/harperDBCallout.js#L28)):*
> ```JavaScript
>         json: true
>     });
>     db.request(operation, true)
> ```

This was throwing an error for me, as the connection in db.connect() above hasn't happened yet.  Either move this to the .then() above or await the db.connect above.  

---


*Comments from [Reviewable](https://reviewable.io/reviews/harperdb/harperdb_studio/19)*

**Comment by elipalmer** [comment]
*[a discussion](https://reviewable.io/reviews/harperdb/harperdb_studio/19#-LEKvMCk2Il-XIjVS68R:-LEKvMCk2Il-XIjVS68S:b-jz6mm7) (no related file):*
Thanks again for this @ethan-arrowood!  I was not able to get it to connect until I made the change described below.  After waiting for the promise to be fulfilled, the studio seems to be working great.  I clicked around with no errors.

---


*Comments from [Reviewable](https://reviewable.io/reviews/harperdb/harperdb_studio/19)*

**Comment by Ethan-Arrowood** [comment]
Major merge conflicts. Going to port work to a new branch off of the most recent master. Will do the same for other broken PRs.

**Comment by elipalmer** [comment]
Closing this PR per the label.

**Pull request closed without merging**
